import { Course, VaultFile, Participant, ChatMessage, User, NotificationItem, AuditLog } from './types';

export const PRESET_USERS: User[] = [
  {
    id: 'usr_admin_01',
    name: 'Rajesh Bhardwaj',
    email: 'rajesh.bhardwaj@bhugarv.com',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200',
    role: 'admin',
    department: 'Bhugarv Geosolution Executive & IT Admin',
    isLoggedIn: true,
    password: 'password123',
    registeredDevice: 'windows',
    location: 'Dehradun Geophysics HQ (India)',
    ipAddress: '103.24.112.45',
    activeStatus: 'online',
    createdAt: '2026-01-10',
  },
  {
    id: 'usr_teacher_01',
    name: 'Dr. Sarah Lin',
    email: 'sarah.lin@bhugarv.com',
    phone: '+1 (555) 382-9102',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    role: 'teacher',
    department: 'Geology & Geophysics Department',
    isLoggedIn: false,
    password: 'password123',
    registeredDevice: 'windows',
    location: 'Delhi NCR Field Station (India)',
    ipAddress: '122.160.18.9',
    activeStatus: 'online',
    createdAt: '2026-02-15',
  },
  {
    id: 'usr_student_01',
    name: 'Alex Rivera',
    email: 'alex.rivera@bhugarv.com',
    phone: '+1 (555) 892-1144',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    role: 'student',
    department: 'GIS & Remote Sensing Batch A',
    isLoggedIn: false,
    password: 'password123',
    registeredDevice: 'android',
    location: 'Bangalore Tech Center (India)',
    ipAddress: '157.48.21.101',
    activeStatus: 'online',
    createdAt: '2026-03-01',
  },
  {
    id: 'usr_student_02',
    name: 'Priya Sharma',
    email: 'priya.sharma@bhugarv.com',
    phone: '+91 98112 23344',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    role: 'student',
    department: 'Hydrology & Structural Engineering',
    isLoggedIn: false,
    password: 'password123',
    registeredDevice: 'android',
    location: 'Mumbai Coastal Survey Camp (India)',
    ipAddress: '115.240.88.33',
    activeStatus: 'idle',
    createdAt: '2026-03-05',
  },
  {
    id: 'usr_student_03',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@bhugarv.com',
    phone: '+91 97722 55110',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    role: 'student',
    department: 'Geothermal Energy Exploration',
    isLoggedIn: false,
    password: 'password123',
    registeredDevice: 'web',
    location: 'Kolkata Remote Lab (India)',
    ipAddress: '182.72.10.55',
    activeStatus: 'online',
    createdAt: '2026-03-12',
  },
  {
    id: 'usr_teacher_02',
    name: 'Prof. Ananya Roy',
    email: 'ananya.roy@bhugarv.com',
    phone: '+91 99001 88221',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    role: 'teacher',
    department: 'Hydrology & Water Table Mapping',
    isLoggedIn: false,
    password: 'password123',
    registeredDevice: 'windows',
    location: 'Dehradun Geophysics HQ (India)',
    ipAddress: '103.24.112.48',
    activeStatus: 'offline',
    createdAt: '2026-02-20',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    title: '🌐 Live Field Session Scheduled',
    body: 'Dr. Sarah Lin has scheduled a live geophysics classroom session on Seismic Wave Spectral Analysis today at 4:00 PM IST.',
    senderName: 'Dr. Sarah Lin',
    senderRole: 'teacher',
    targetPlatform: 'all',
    targetRole: 'all',
    timestamp: '10:30 AM',
    read: false,
    category: 'class',
  },
  {
    id: 'notif_2',
    title: '🔔 System Maintenance Alert (Windows & Android)',
    body: 'Bhugarv FCM notification dispatch system upgraded. Android and Windows push alerts are active.',
    senderName: 'Rajesh Bhardwaj',
    senderRole: 'admin',
    targetPlatform: 'all',
    targetRole: 'all',
    timestamp: 'Yesterday',
    read: true,
    category: 'system',
  },
  {
    id: 'notif_3',
    title: '📁 New Vault Document Uploaded',
    body: 'GIS_Spatial_Analysis_Field_Report_2026.pdf has been added to the Class File Vault.',
    senderName: 'Dr. Sarah Lin',
    senderRole: 'teacher',
    targetPlatform: 'android',
    targetRole: 'student',
    timestamp: '2 days ago',
    read: true,
    category: 'vault',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_1',
    action: 'ROLE_ASSIGNMENT',
    performedBy: 'Rajesh Bhardwaj (Admin)',
    targetUser: 'Dr. Sarah Lin',
    timestamp: '2026-07-03 11:20:00',
    details: 'Assigned Senior Instructor & Teacher Role with Course Management Permissions.',
  },
  {
    id: 'log_2',
    action: 'FCM_PUSH_DISPATCH',
    performedBy: 'Rajesh Bhardwaj (Admin)',
    timestamp: '2026-07-03 10:15:00',
    details: 'Broadcasted FCM push alert to all Windows and Android users regarding live field session.',
  },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'crs_101',
    title: 'Advanced Neural Networks & Generative AI',
    code: 'CS-4820',
    description: 'Deep dive into transformer architectures, attention mechanisms, fine-tuning large language models, and real-time inference optimization.',
    instructor: 'Dr. Sarah Lin',
    instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    category: 'Computer Science',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800',
    duration: '12 Weeks',
    totalModules: 8,
    enrolledStudents: 142,
    featuredVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    syllabus: [
      { id: 'syl_1', title: 'Module 1: Mathematical Foundations of Attention', duration: '45 mins', completed: true, videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4' },
      { id: 'syl_2', title: 'Module 2: Multi-Head Self Attention & Positional Encoding', duration: '55 mins', completed: true, videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4' },
      { id: 'syl_3', title: 'Module 3: Pre-training vs Instruction Fine-Tuning (RLHF)', duration: '60 mins', completed: false, videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4' },
      { id: 'syl_4', title: 'Module 4: Quantization & ONNX Model Compression', duration: '50 mins', completed: false },
      { id: 'syl_5', title: 'Module 5: Deploying LLM Services on Edge Runtimes', duration: '65 mins', completed: false },
    ],
  },
  {
    id: 'crs_102',
    title: 'Distributed Systems & Microservice Architecture',
    code: 'CS-3910',
    description: 'Master consensus algorithms (Raft, Paxos), gRPC communication, message brokers (Kafka), and event-driven microservice orchestration.',
    instructor: 'Prof. Marcus Vance',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    category: 'Software Engineering',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
    duration: '10 Weeks',
    totalModules: 6,
    enrolledStudents: 98,
    featuredVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    syllabus: [
      { id: 'syl_201', title: 'Lecture 1: CAP Theorem & Consistency Models', duration: '50 mins', completed: true, videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4' },
      { id: 'syl_202', title: 'Lecture 2: Raft Consensus & Leader Election', duration: '58 mins', completed: true, videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4' },
      { id: 'syl_203', title: 'Lecture 3: High-Throughput Streaming with Kafka', duration: '70 mins', completed: false },
    ],
  },
  {
    id: 'crs_103',
    title: 'Modern UI/UX Systems & Spatial Design',
    code: 'DES-2040',
    description: 'Learn scalable design token architectures, accessibility standards (WCAG 2.2), responsive component composition, and spatial UI interaction.',
    instructor: 'Elena Rostova',
    instructorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    category: 'Design & Media',
    thumbnail: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=800',
    duration: '8 Weeks',
    totalModules: 5,
    enrolledStudents: 180,
    featuredVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    syllabus: [
      { id: 'syl_301', title: 'Session 1: Typography Scales & Modular Grids', duration: '40 mins', completed: true, videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4' },
      { id: 'syl_302', title: 'Session 2: Design Systems & Figma Variables', duration: '52 mins', completed: false },
    ],
  }
];

export const MOCK_VAULT_FILES: VaultFile[] = [
  {
    id: 'fl_apk_01',
    name: 'Bhugarv_Geosolution_v2.4_Android.apk',
    sizeBytes: 48200000,
    type: 'apk',
    category: 'apps',
    uploadDate: '2026-07-03',
    uploaderName: 'Rajesh Bhardwaj (IT Admin)',
    uploaderRole: 'admin',
    allowedRoles: ['admin', 'teacher', 'student'],
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    starred: true,
    downloadCount: 230,
    tags: ['Android APK', 'Official App Package', 'Mobile Installer'],
  },
  {
    id: 'fl_01',
    name: 'CS4820_Transformer_Architecture_Slides.pdf',
    sizeBytes: 14200000,
    type: 'pdf',
    category: 'slides',
    uploadDate: '2026-07-02',
    uploaderName: 'Dr. Sarah Lin',
    uploaderRole: 'teacher',
    allowedRoles: ['teacher', 'student'],
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    starred: true,
    downloadCount: 42,
    tags: ['AI', 'Transformers', 'Lecture Slides'],
  },
  {
    id: 'fl_02',
    name: 'Class_Recording_2026-07-01_Live_Demo.mp4',
    sizeBytes: 248000000,
    type: 'mp4',
    category: 'recordings',
    uploadDate: '2026-07-01',
    uploaderName: 'Dr. Sarah Lin',
    uploaderRole: 'teacher',
    allowedRoles: ['teacher', 'student'],
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    starred: false,
    downloadCount: 89,
    tags: ['Video', 'Live Meeting', 'Recording'],
  },
  {
    id: 'fl_03',
    name: 'Assignment_3_PyTorch_Attention_Implementation.zip',
    sizeBytes: 8500000,
    type: 'zip',
    category: 'assignments',
    uploadDate: '2026-06-28',
    uploaderName: 'Dr. Sarah Lin',
    uploaderRole: 'teacher',
    allowedRoles: ['teacher', 'student'],
    url: '#',
    starred: true,
    downloadCount: 115,
    tags: ['Homework', 'PyTorch', 'Code Starter'],
  },
  {
    id: 'fl_04',
    name: 'raft_consensus_benchmarks.py',
    sizeBytes: 12400,
    type: 'py',
    category: 'code_snippets',
    uploadDate: '2026-06-25',
    uploaderName: 'Prof. Marcus Vance',
    uploaderRole: 'teacher',
    allowedRoles: ['teacher', 'student'],
    url: '#',
    starred: false,
    downloadCount: 31,
    tags: ['Python', 'Distributed Systems'],
  },
  {
    id: 'fl_05',
    name: 'Exam_Preparation_Cheatsheet_2026.pdf',
    sizeBytes: 4500000,
    type: 'pdf',
    category: 'lecture_notes',
    uploadDate: '2026-06-20',
    uploaderName: 'Alex Rivera',
    uploaderRole: 'student',
    allowedRoles: ['teacher', 'student'],
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    starred: true,
    downloadCount: 67,
    tags: ['Student Notes', 'Cheatsheet'],
  }
];

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'p_host',
    name: 'Dr. Sarah Lin',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    isLocal: false,
    isMuted: false,
    isVideoOff: false,
    isScreenSharing: false,
    isHandRaised: false,
    isSpeaking: true,
    connectionQuality: 'excellent',
  },
  {
    id: 'p_2',
    name: 'Alex Rivera',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    isLocal: false,
    isMuted: true,
    isVideoOff: false,
    isScreenSharing: false,
    isHandRaised: true,
    isSpeaking: false,
    connectionQuality: 'excellent',
  },
  {
    id: 'p_3',
    name: 'Priya Sharma',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    isLocal: false,
    isMuted: false,
    isVideoOff: false,
    isScreenSharing: false,
    isHandRaised: false,
    isSpeaking: false,
    connectionQuality: 'good',
  },
  {
    id: 'p_4',
    name: 'Liam Chen',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    isLocal: false,
    isMuted: true,
    isVideoOff: true,
    isScreenSharing: false,
    isHandRaised: false,
    isSpeaking: false,
    connectionQuality: 'good',
  }
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg_1',
    senderName: 'Dr. Sarah Lin',
    senderRole: 'teacher',
    senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    message: 'Welcome everyone! Today we are discussing Self-Attention matrices and Multi-Head projection layers.',
    timestamp: '10:02 AM',
  },
  {
    id: 'msg_2',
    senderName: 'Alex Rivera',
    senderRole: 'student',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    message: 'Is the scaling factor 1/√d_k used to prevent softmax saturation in large dimensions?',
    timestamp: '10:05 AM',
    isQA: true,
    upvotes: 8,
    upvotedByMe: true,
  },
  {
    id: 'msg_3',
    senderName: 'Priya Sharma',
    senderRole: 'student',
    senderAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    message: 'I uploaded the summary notes for Module 2 in the Class File Vault!',
    timestamp: '10:08 AM',
    attachment: {
      name: 'Exam_Preparation_Cheatsheet_2026.pdf',
      size: '4.5 MB',
      type: 'pdf',
    }
  }
];
